---
# This Playbook runs all the common plays in the deployment 

#  puppet managed
#- name: Create the hosts file for all machines
#  template: src=hosts.j2 dest=/etc/hosts

# Not sure why apt repository not working... but it botches so we do this with command
- name: Create the repository for 10Gen
  sudo: true
  shell: "/bin/echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list"

- name: Install the 10gen key
  command: /usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  sudo: true

# We'll use the ubu user.
#- name: Create the mongod user
#  user: name=mongod comment="MongoD"

- name: Install the mongodb package
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
   - mongodb-10gen
   - bc
   - python-pip
#   # Should I pin it?
#   #- mongodb-10gen==2.2.3

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongodb group=mongodb state=directory

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no 

# OK, the ubuntu mongo dumps /etc/mongodb.conf where we don't want it
#  and starts up the process, messing with our own ability to stop it.

#- name: Ensure UBU mongo is not bloody running
#  sudo: true
#  service: name=mongodb state=stopped

#- name: Ensure UBU mongo is out of my init...
#  file: dest=/etc/init/mongodb state=absent

#- name: Ensure UBU mongo.conf is out of my init...
#  file: dest=/etc/mongodb.conf state=absent

#- name: Ensure UBU upstart mongo.conf is out of my init...
#  file: dest=/etc/init/mongodb.conf state=absent

#- name: Install proper mongo.conf
#  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf backup=yes

# Force configured port/default to ours.
#   If this runs twice, it puts in the port 2x, and the service will silently die.
- name: Edit stock mongo.conf with ourt port
  lineinfile: dest=/etc/mongodb.conf backup=yes regexp='^port = 27017' insertafter='^#port = 27017' line='port = {{ mongod_port }}' owner=root group=root

- name: Now start my mongo
  sudo: true
  service: name=mongodb state=restarted
