---
#This Playbook configures the mongos service of mongodb

- name: Create the mongos startup file
  file: src=/lib/init/upstart-job dest=/etc/init.d/mongos state=link

- name: Create the mongos upstart config file
  template: src=mongos.j2 dest=/etc/init/mongs.conf mode=0655

- name: Create the mongos configuration file
  template: src=mongos.conf.j2 dest=/etc/mongos.conf

- name: Copy the keyfile for authentication
  copy: src=roles/mongod/files/secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400

- name: Start the mongos service
  command: creates=/var/run/mongos.pid /usr/sbin/service mongos start
- name: pause
  pause: seconds=20

- name: copy the file for shard test 
  template: src=testsharding.j2 dest=/tmp/testsharding.js

- name: copy the file enable  sharding 
  template: src=enablesharding.j2 dest=/tmp/enablesharding.js
